#!/usr/bin/env bash
sudo apt install software-properties-common
sudo apt-add-repository --yes ppa:ansible/ansible
sudo apt-add-repository --yes ppa:neovim-ppa/unstable
sudo apt update
sudo apt install --yes ansible curl git neovim
export N_PREFIX="$HOME/.local/n"
export PATH=~/.local/.npm-global/bin:$PATH
export PATH=~/.local/n/bin:$PATH
