- name: Installing stow
  become: true
  ansible.builtin.apt: name=stow
  tags:
    - install
    - dotfiles
    - stow

- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: "git@github.com:byodian/dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: true
    update: true
    accept_hostkey: true
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  ansible.builtin.shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
