- name: Install packages (tmux fzf bat htop tldr stow tig xclip fd-find)
  become: true
  ansible.builtin.apt:
    name:
      [
        "tmux",
        "fzf",
        "bat",
        "htop",
        "tldr",
        "stow",
        "tig",
        "xclip",
        "fd-find",
      ]
  tags:
    - install
    - productivity
